# Site settings
title: the Blue Dragon
email: 
description: > 
  Just a place to write something
baseurl: "" 
url: "http://quheng.github.io" 
github_username: quheng

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]